"""add currency to orders

Revision ID: cd6f137d62f4
Revises: 944b6ef59200
Create Date: 2025-12-22 17:36:45.739727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd6f137d62f4'
down_revision: Union[str, None] = '944b6ef59200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_items_variant_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'product_variants', ['variant_id'], ['id'])
    op.alter_column('carts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('carts_user_id_fkey', 'carts', type_='foreignkey')
    op.drop_column('carts', 'created_at')
    op.add_column('orders', sa.Column('currency', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'currency')
    op.add_column('carts', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key('carts_user_id_fkey', 'carts', 'users', ['user_id'], ['id'])
    op.alter_column('carts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_variant_id_fkey', 'cart_items', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
