"""finalize orders payments cart schema

Revision ID: d048331a6f6f
Revises: cd6f137d62f4
Create Date: 2025-12-23 00:32:51.428761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd048331a6f6f'
down_revision: Union[str, None] = 'cd6f137d62f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'currency')
    op.alter_column('payments', 'razorpay_order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'razorpay_order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('orders', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
